// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsmyavqwsypibafaeuxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzbXlhdnF3c3lwaWJhZmFldXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTM0MjUsImV4cCI6MjA1ODQ4OTQyNX0.o9ir0HVIt0gnTl12y-BC9gdbwFfPI19mPU7OxOStEC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);